version: '3.5'
services:
  app:
    environment:
      - DB_NAME=interview_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=configuration.settings.development
      - WOO_CONSUMER_KEY=$WOO_CONSUMER_KEY
      - WOO_CONSUMER_SECRET=$WOO_CONSUMER_SECRET
    build: .
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    ports:
      - 8009:80
    links:
      - db

  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_DB=interview_db
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432