version: 2
jobs:
  build:
    working_directory: ~/mpesa_api
    docker:
      - image: circleci/python:3.6.1
        environment:
          DB_USER: circleci
          DB_NAME: circle_test
          DB_PASSWORD: "root"
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          WOO_CONSUMER_KEY: "Test Key"
          WOO_CONSUMER_SECRET: "Test Secret"
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "root"

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codecov


      # run tests!
      - run:
          name: run app tests
          command: |
            . venv/bin/activate
            coverage run manage.py test --settings=configuration.settings.ci
            coverage report
            coverage xml
      - run:
          name: upload codecov report
          command: bash <(curl -s https://codecov.io/bash) -t 9efa1916-9954-4569-8380-c342c455b022